### ISSUE TITLE
ready callback makes requests

### ISSUE THREAD

**Issue by pushred** [SparkartGroupInc/universe.js#4]
The ready callback currently results in requests to the fanclub and account endpoints (if logged in), and returns the value of `universe.context.universe.customer` inconsistently. These should be fetched separately and (ideally) emit a ready event only once both responses are available.

I'm trying to execute callbacks of my own, passing along the customer context.

**Comment by joanniclaborde** [comment]
```javascript
var universe = new Universe(…);

universe.on(‘ready’, callback1);
universe.on(‘ready’, callback2);

universe.ready(callback3);
universe.ready(callback4);

universe.init(); // or something better?
```

**Comment by pushred** [comment]
I like consolidating all event emits in an `on` method, that's consistent with the Blocks modules and jQuery. And it doesn't muddle events and methods. Why not just accept a callback function after the config object? That would be consistent with Backbone and jQuery plugins.

**Comment by joanniclaborde** [comment]
Sure, although it feels weird to be able to specify a ready callback in 3 different manners. And do we always want to fetch the fanclub and customer when the object is instantiated? It's really a usage question, you have more experience than me with using libraries like this...

**Comment by pushred** [comment]
Sorry I was misunderstanding how init actually happens, I don't see a problem with the initial requests happening upon instantiation if we can pass that object to all of the dependencies as I did on Aldean.

Given that we should only support `on` and nothing else. Can you do this in another branch so we don't break Aldean, etc? I don't want you to have to keep updating those sites as this is iterated upon.
